spring:
  application:
    name: account-service
  
server:
  port: 1111

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://13.233.163.18:8761/eureka}
  instance:
    prefer-ip-address: true
